# Generated by Django 3.2.16 on 2022-12-25 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mfadmin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_key', models.CharField(default='b5c1a0f55e', max_length=10, unique=True)),
                ('name', models.CharField(default='', max_length=250)),
                ('username', models.CharField(blank=True, default='', max_length=100, unique=True)),
                ('phone', models.CharField(default='', max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_pickupman', models.BooleanField(default=False)),
                ('is_normaluser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', mfadmin.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mfadmin.user')),
                ('aadhaar_card', models.CharField(default='', max_length=12)),
                ('pan_card', models.CharField(default='', max_length=20)),
                ('account_no', models.TextField(default=0, max_length='100', unique=True)),
                ('total_amount', models.FloatField(default=0)),
                ('address', models.TextField(default='')),
                ('area', models.CharField(default='', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
            ],
        ),
        migrations.CreateModel(
            name='PickupMan',
            fields=[
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mfadmin.user')),
                ('aadhaar_card', models.CharField(default='', max_length=12)),
                ('total_amount', models.FloatField(default=0)),
                ('address', models.TextField(default='')),
                ('area', models.CharField(default='', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField(null=True)),
                ('otp_time', models.DateTimeField(null=True)),
                ('counter', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], default='', max_length=250)),
                ('transaction_amount', models.FloatField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pickup_man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mfadmin.pickupman')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mfadmin.normaluser')),
            ],
        ),
    ]
